[package]
name = "task-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = {version = "0.4.40", features = ["serde"]}
serde_json = {version="1.0.99"}
serde = {version="1.0.99", features=["derive"]}
